title: Austin Portfolio
description: Hola, bienvenidos, amigos!
author: Anil Thapa
email: anilthapa1.at23@gmail.com

baseurl: "" # Leave blank unless hosted in a subdirectory
url: "https://axt0895.github.io" # Replace with your GitHub Pages URL

theme: jekyll-theme-minimal # Use GitHub Pages built-in themes

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  github: https://github.com/axt0895
  linkedin: https://www.linkedin.com/in/anil-thapa-354b23353/

# Optional settings for pagination or other features can go here.
